[package]
name = "your_project_name" 
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.4"
spl-token-2022 = { version = "0.3.3", features = ["no-entrypoint"] }
spl-associated-token-account-2022 = { version = "0.1.1", features = ["no-entrypoint"] }
spl-memo = { version = "3.0.1", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
